# Dependency Review Configuration
# This file configures which vulnerabilities to allow in dependency-review-action
# See: https://github.com/actions/dependency-review-action#configuration-options

# Fail on vulnerabilities of this severity or higher
fail-on-severity: moderate

# Allow specific GitHub Security Advisories (GHSAs)
# Add GHSA IDs here to temporarily allow known vulnerabilities
# Example format: GHSA-xxxx-xxxx-xxxx
# To find the GHSA ID, check your GitHub Security tab or Dependabot alerts
# allow-ghsas:
#   - GHSA-xxxx-xxxx-xxxx

# Allow specific licenses (if needed)
# allow-licenses:
#   - MIT
#   - Apache-2.0

# Deny specific licenses (if needed)
# deny-licenses:
#   - GPL-3.0

# Allow packages with vulnerabilities (use sparingly)
# Note: This allows ALL vulnerabilities in these packages
allow-dependencies-licenses:
  - pkg:maven/org.eclipse.jetty/jetty-http@11.0.26

# Comment or reason for exceptions
# Jetty 11.0.26 is the latest version compatible with Dropwizard 4.0.16
# Waiting for Dropwizard to upgrade to Jetty 12 which fixes known vulnerabilities
