name: Quick Security Check

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'pom.xml'

permissions:
  contents: read
  pull-requests: write

jobs:
  quick-security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

    - name: Run SpotBugs Security Check
      run: |
        mvn compile spotbugs:check \
          -Dspotbugs.effort=Max \
          -Dspotbugs.threshold=Low \
          -Dspotbugs.includeFilterFile=spotbugs-security.xml \
          -q

    - name: Check for known vulnerable dependencies (quick)
      run: |
        echo "Checking for known vulnerable dependencies..."
        # Use Maven versions plugin to check for updates and security issues
        mvn versions:display-dependency-updates -DlogResults=false -q | grep -E "(SECURITY|CVE)" || true

        # Alternative: Use GitHub Security Advisory Database via npm audit (if package.json exists)
        if [ -f "package.json" ]; then
          npm audit --audit-level moderate || echo "No package.json or npm issues found"
        fi

        # Check for dependencies with known issues using mvn dependency:analyze
        echo "Analyzing dependency tree for potential issues..."
        mvn dependency:analyze -q

    - name: Validate Maven dependencies
      run: mvn dependency:analyze -q

    - name: Check for hardcoded secrets (basic)
      run: |
        echo "Checking for potential hardcoded secrets..."
        # Simple regex patterns for common secrets
        if grep -r -E "(password|secret|key|token)\s*[:=]\s*['\"][^'\"]{8,}" src/ --include="*.java" --exclude-dir=test; then
          echo "⚠️  Potential hardcoded secrets found!"
          exit 1
        else
          echo "✅ No obvious hardcoded secrets detected"
        fi
